Repository JNU-econovation/HyunSolution_BE, pull requests merged in 2024-12, with the labels that each got.

#71 fix: findUnmatchedAndCreatedWithinLastDay 쿼리 수정
  Dockerfile
  docker-compose.yml
  src/main/java/com/hyunsolution/dangu/DanguApplication.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#75 deploy: nginx 설정
  Dockerfile
  docker-compose.yml
  nginx/app.conf
Labels: 🌏 Deploy

#77 deploy: docker-compose.yml 수정
  docker-compose.yml
Labels: 🐞 BugFix, 🌏 Deploy

#73 refactor: 날짜 비교 쿼리 개선
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
Labels: 🔨 Refactor

#79 fix: 워크스페이스 목록 조회 안되는 버그
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: 🐞 BugFix

#85 deploy: docker-compose.yml 경로 변경
  docker-compose.yml
Labels: 🌏 Deploy

#83 feature: 채팅 조회시 상대방 이름 값 응답으로 보내기
  src/main/java/com/hyunsolution/dangu/chatRoom/domain/ChatRoomRepository.java
  src/main/java/com/hyunsolution/dangu/chatting/controller/ChattingController.java
  src/main/java/com/hyunsolution/dangu/chatting/dto/response/ChattingsDto.java
  src/main/java/com/hyunsolution/dangu/chatting/dto/response/GetChatRoomsResponse.java
  src/main/java/com/hyunsolution/dangu/chatting/dto/response/GetChattingsResponse.java
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
Labels: ✨ Feature
