Repository JNU-econovation/HyunSolution_BE, pull requests merged in 2024-10, with the labels that each got.

#11 feat: 매칭 구현
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/hyunsolutiondemo/dangu/DanguApplication.java
  src/main/java/com/hyunsolutiondemo/dangu/chatlog/Chatlog.java
  src/main/java/com/hyunsolutiondemo/dangu/chatting/Chatting.java
  src/main/java/com/hyunsolutiondemo/dangu/common/apiResponse/ApiResponse.java
  src/main/java/com/hyunsolutiondemo/dangu/common/apiResponse/CustomException.java
  src/main/java/com/hyunsolutiondemo/dangu/common/apiResponse/ErrorCode.java
  src/main/java/com/hyunsolutiondemo/dangu/common/apiResponse/ExceptionDto.java
  src/main/java/com/hyunsolutiondemo/dangu/common/apiResponse/GlobalExceptionHandler.java
  src/main/java/com/hyunsolutiondemo/dangu/participant/controller/ParticipantController.java
  src/main/java/com/hyunsolutiondemo/dangu/participant/domain/Participant.java
  src/main/java/com/hyunsolutiondemo/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolutiondemo/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolutiondemo/dangu/user/domain/User.java
  src/main/java/com/hyunsolutiondemo/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolutiondemo/dangu/workspace/domain/WorkspaceRepository.java
  src/main/resources/application.yml
  src/test/java/com/hyunsolutiondemo/dangu/DanguApplicationTests.java
Labels: ✨ Feature

#12 feat: 게임 등록
  build.gradle
  src/main/java/com/hyunsolution/dangu/DanguApplication.java
  src/main/java/com/hyunsolution/dangu/chatlog/Chatlog.java
  src/main/java/com/hyunsolution/dangu/chatting/Chatting.java
  src/main/java/com/hyunsolution/dangu/common/apiResponse/ApiResponse.java
  src/main/java/com/hyunsolution/dangu/common/apiResponse/CustomException.java
  src/main/java/com/hyunsolution/dangu/common/apiResponse/ErrorCode.java
  src/main/java/com/hyunsolution/dangu/common/apiResponse/ExceptionDto.java
  src/main/java/com/hyunsolution/dangu/common/apiResponse/GlobalExceptionHandler.java
  src/main/java/com/hyunsolution/dangu/common/config/SwaggerConfig.java
  src/main/java/com/hyunsolution/dangu/common/exception/BaseErrorCode.java
  src/main/java/com/hyunsolution/dangu/common/exception/CustomException.java
  src/main/java/com/hyunsolution/dangu/common/exception/ExceptionDto.java
  src/main/java/com/hyunsolution/dangu/common/exception/GlobalError.java
  src/main/java/com/hyunsolution/dangu/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hyunsolution/dangu/participant/Participant.java
  src/main/java/com/hyunsolution/dangu/participant/controller/ParticipantController.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/user/domain/User.java
  src/main/java/com/hyunsolution/dangu/user/domain/UserRepository.java
  src/main/java/com/hyunsolution/dangu/user/exception/UserError.java
  src/main/java/com/hyunsolution/dangu/user/exception/UserNotFoundException.java
  src/main/java/com/hyunsolution/dangu/workspace/controller/WorkSpaceController.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
  src/main/java/com/hyunsolution/dangu/workspace/dto/request/CreateWorkspaceRequest.java
  src/main/java/com/hyunsolution/dangu/workspace/dto/response/GetWorkspacesResponse.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
  src/test/java/com/hyunsolution/dangu/DanguApplicationTests.java
Labels: ✨ Feature

#22 deploy: springBoot 도커 이미지 태그 수정
  docker-compose.yml
Labels: 🌏 Deploy

#24 fix: application.yml 수정
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🐞 BugFix
