Repository JNU-econovation/HyunSolution_BE, pull requests merged in 2024-11, with the labels that each got.

#18 refactor: Entity 생성자 private으로 수정
  src/main/java/com/hyunsolution/dangu/chatlog/Chatlog.java
  src/main/java/com/hyunsolution/dangu/chatting/Chatting.java
  src/main/java/com/hyunsolution/dangu/participant/Participant.java
  src/main/java/com/hyunsolution/dangu/user/domain/User.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
Labels: 🔨 Refactor

#32 feature: 로그인 기능 구현
  src/main/java/com/hyunsolution/dangu/user/controller/UserController.java
  src/main/java/com/hyunsolution/dangu/user/domain/UserRepository.java
  src/main/java/com/hyunsolution/dangu/user/dto/request/LoginRequest.java
  src/main/java/com/hyunsolution/dangu/user/dto/response/LoginResponse.java
  src/main/java/com/hyunsolution/dangu/user/exception/UserError.java
  src/main/java/com/hyunsolution/dangu/user/exception/UserWrongPasswordException.java
  src/main/java/com/hyunsolution/dangu/user/service/UserService.java
Labels: ✨ Feature

#27 feature: 게임방 목록 조회 로직 수정
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#38 deploy: CI/CD 수정
  .github/workflows/prod-deploy-container.yml
Labels: 🌏 Deploy

#47 feature: 채팅 입장 (#45)
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
Labels: ✨ Feature

#52 deploy: prod-deploy-container 복구 (#51)
  .github/workflows/prod-deploy-container.yml
Labels: 🐞 BugFix

#54 feat: 채팅 목록 조회 정렬기준 변경
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
  src/main/java/com/hyunsolution/dangu/participant/controller/ParticipantController.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/user/domain/UserRepository.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#57 feat: 참여자 매칭 취소
  src/main/java/com/hyunsolution/dangu/participant/controller/ParticipantController.java
  src/main/java/com/hyunsolution/dangu/participant/domain/Participant.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/dto/request/UpdateParticipantMatchRequest.java
  src/main/java/com/hyunsolution/dangu/participant/exception/AlreadyMatchedException.java
  src/main/java/com/hyunsolution/dangu/participant/exception/ParticipantError.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
Labels: ✨ Feature

#64 feature: 매칭 현황 기능 구현 및 정책정의서 반영
  src/main/java/com/hyunsolution/dangu/chatRoom/domain/ChatRoom.java
  src/main/java/com/hyunsolution/dangu/chatlog/domain/ChatLog.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/Chatting.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/MessageType.java
  src/main/java/com/hyunsolution/dangu/chatting/dto/response/ChatMessageDetailResponse.java
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
  src/main/java/com/hyunsolution/dangu/common/BaseEntity.java
  src/main/java/com/hyunsolution/dangu/participant/controller/ParticipantController.java
  src/main/java/com/hyunsolution/dangu/participant/domain/Participant.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/dto/response/GetMatchStatusResponse.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/user/domain/User.java
  src/main/java/com/hyunsolution/dangu/user/exception/UserError.java
  src/main/java/com/hyunsolution/dangu/workspace/controller/WorkSpaceController.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: ✨ Feature

#67 BugFix: 소켓 에러 해결 (#66)
  src/main/java/com/hyunsolution/dangu/chatting/domain/Chatting.java
  src/main/java/com/hyunsolution/dangu/common/BaseEntity.java
  src/main/resources/static/index.html
Labels: 🐞 BugFix

#69 feature: 채팅방목록 조회 에러 해결(#68)
  src/main/java/com/hyunsolution/dangu/chatting/domain/Chatting.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/ChattingRepository.java
Labels: 🐞 BugFix

#65 feat: 워크 스페이스(매칭) 목록조회 response에 isOwn추가
  src/main/java/com/hyunsolution/dangu/common/BaseEntity.java
  src/main/java/com/hyunsolution/dangu/workspace/controller/WorkSpaceController.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/WorkspaceRepository.java
  src/main/java/com/hyunsolution/dangu/workspace/dto/response/GetWorkspacesResponse.java
  src/main/java/com/hyunsolution/dangu/workspace/exception/WorkspaceAlreadyExistsException.java
  src/main/java/com/hyunsolution/dangu/workspace/exception/WorkspaceError.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: ✨ Feature
