Repository JNU-econovation/HyunSolution_BE, pull requests merged in 2025-01, with the labels that each got.

#91 feat: 매칭 확정 시 다른 채팅방 사용 못하게 막기
  src/main/java/com/hyunsolution/dangu/chatRoom/domain/ChatRoomRepository.java
  src/main/java/com/hyunsolution/dangu/chatting/exception/ChatError.java
  src/main/java/com/hyunsolution/dangu/chatting/exception/ChatRoomNotFoundException.java
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/exception/AlreadyMatchedCannotAcceptException.java
  src/main/java/com/hyunsolution/dangu/participant/exception/ParticipantError.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
Labels: ✨ Feature

#93 feat: 당구대 번호 입력 및 점수 입력
  src/main/java/com/hyunsolution/dangu/game/controller/GameController.java
  src/main/java/com/hyunsolution/dangu/game/domain/Game.java
  src/main/java/com/hyunsolution/dangu/game/domain/GameRepository.java
  src/main/java/com/hyunsolution/dangu/game/dto/request/GetGameScoreRequest.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/EnterGameRoomResponse.java
  src/main/java/com/hyunsolution/dangu/game/service/GameService.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
Labels: ✨ Feature

#90 feat: 비밀번호 암호화
  build.gradle
  src/main/java/com/hyunsolution/dangu/common/config/SecurityConfig.java
  src/main/java/com/hyunsolution/dangu/user/service/UserService.java
Labels: ✨ Feature

#96 feat: 대전 페이지 목록 조회 및 부가기능 구현
  src/main/java/com/hyunsolution/dangu/chatlog/domain/ChatLogRepository.java
  src/main/java/com/hyunsolution/dangu/chatting/controller/ChattingController.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/MessageType.java
  src/main/java/com/hyunsolution/dangu/game/controller/GameController.java
  src/main/java/com/hyunsolution/dangu/game/domain/Game.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/EnterGameRoomResponse.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/GetGameListResponse.java
  src/main/java/com/hyunsolution/dangu/game/service/GameService.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
Labels: ✨ Feature

#97 feature: 웹소켓 연결 끊길 시 채팅 목록 unreadCount 업데이트 로직 구현
  src/main/java/com/hyunsolution/dangu/chatting/controller/ChattingController.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/ChatSession.java
  src/main/java/com/hyunsolution/dangu/chatting/domain/ChattingRepository.java
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
  src/main/java/com/hyunsolution/dangu/common/config/webSocket/WebSocketListenerConfig.java
  src/main/java/com/hyunsolution/dangu/common/config/webSocket/WebSocketSwaggerDocsController.java
  src/main/resources/static/index.html
Labels: ✨ Feature

#99 feat: 승패 계산 및 결제 및 기타 오류 해결
  src/main/java/com/hyunsolution/dangu/game/controller/GameController.java
  src/main/java/com/hyunsolution/dangu/game/domain/Game.java
  src/main/java/com/hyunsolution/dangu/game/domain/GameRepository.java
  src/main/java/com/hyunsolution/dangu/game/domain/GameResult.java
  src/main/java/com/hyunsolution/dangu/game/domain/GameResultRepository.java
  src/main/java/com/hyunsolution/dangu/game/dto/GameResultsDto.java
  src/main/java/com/hyunsolution/dangu/game/dto/GetBillingDto.java
  src/main/java/com/hyunsolution/dangu/game/dto/GetGameListDto.java
  src/main/java/com/hyunsolution/dangu/game/dto/request/MoreGameRequest.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/EnterGameRoomResponse.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/GetBillingResponse.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/GetGameListResponse.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/GetGameResultsResponse.java
  src/main/java/com/hyunsolution/dangu/game/dto/response/MoreGameResponse.java
  src/main/java/com/hyunsolution/dangu/game/exception/GameError.java
  src/main/java/com/hyunsolution/dangu/game/exception/GameNotFoundException.java
  src/main/java/com/hyunsolution/dangu/game/service/GameService.java
  src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
  src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
  src/main/java/com/hyunsolution/dangu/workspace/controller/WorkSpaceController.java
  src/main/java/com/hyunsolution/dangu/workspace/domain/Workspace.java
  src/main/java/com/hyunsolution/dangu/workspace/dto/response/CheckWorkspaceManager.java
  src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
Labels: 🐞 BugFix, ✨ Feature

#101 fix: 채팅목록 조회 otherPeople 오류
  src/main/java/com/hyunsolution/dangu/chatRoom/domain/ChatRoomRepository.java
  src/main/java/com/hyunsolution/dangu/user/service/UserService.java
Labels: 🐞 BugFix

#105 fix: 채팅목록 오류 수정
  src/main/java/com/hyunsolution/dangu/chatting/service/ChattingService.java
Labels: 🐞 BugFix
